config/routes.rb
Rails.application.routes.draw do
  resources :floorplans

  resources :restaurants

  resources :operators
  get "/register" => "operators#new"

  get "/restaurants/:id/floorplans" => "floorplans#new"
  post "/restaurants/:id/floorplans/add" => "floorplans#add"
  put '/restaurants/:id/floorplans/:floorplanId/update' => 'floorplans#update'

  root to: 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

end

app/models/floorplan.rb
class Floorplan < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/floorplans_controller.rb
class FloorplansController < ApplicationController
  before_action :set_floorplan, only: [:show, :edit, :destroy]

  def index
    @floorplans = Floorplan.all
  end

  def add
    floorplan = Floorplan.new
    floorplan.width = params[:width]
    floorplan.height = params[:height]
    floorplan.top = params[:top]
    floorplan.left = params[:left]
    floorplan.background = params[:background]
    floorplan.restaurant_id = params[:id]
    floorplan.save

    render json: { floorplan: floorplan }
  end

  def show
  end

  def new
    @restaurant = Restaurant.find_by id: params[:id]
    @floorplan = Floorplan.new
  end

  def edit
  end

  def update

    floorplan = Floorplan.find_by id: params[:floorplanId]
    floorplan.width = params[:width]
    floorplan.height = params[:height]
    floorplan.top = params[:top]
    floorplan.left = params[:left]
    floorplan.background = params[:background]
    floorplan.restaurant_id = params[:id]
    floorplan.save

    render json: { floorplan: floorplan }
  end

  def create
    @floorplan = Floorplan.new(floorplan_params)

    respond_to do |format|
      if @floorplan.save
        format.html { redirect_to @floorplan, notice: 'Floorplan was successfully created.' }
        format.json { render :show, status: :created, location: @floorplan }
      else
        format.html { render :new }
        format.json { render json: @floorplan.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @floorplan.destroy
    respond_to do |format|
      format.html { redirect_to floorplans_url, notice: 'Floorplan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    def set_floorplan
      @floorplan = Floorplan.find(params[:id])
    end

    def floorplan_params
      params.require(:floorplan).permit(:top, :left, :restaurant_id)
    end

end

app/helpers/floorplans_helper.rb
module FloorplansHelper
end

app/views/floorplans/_form.html.erb
<%= form_for(floorplan) do |f| %>
  <% if floorplan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(floorplan.errors.count, "error") %> prohibited this floorplan from being saved:</h2>

      <ul>
      <% floorplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :top %>
    <%= f.number_field :top %>
  </div>

  <div class="field">
    <%= f.label :left %>
    <%= f.number_field :left %>
  </div>

  <div class="field">
    <%= f.label :restaurant_id %>
    <%= f.number_field :restaurant_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/floorplans/edit.html.erb
<h1>Editing Floorplan</h1>

<%= render 'form', floorplan: @floorplan %>

<%= link_to 'Show', @floorplan %> |
<%= link_to 'Back', floorplans_path %>

app/views/floorplans/new.html.erb
<div id="menue-left" class="row">
  <div class="draggable table col-lg-2">Table</div>
  <div class="draggable station col-lg-2">Waiter Station</div>
  <div class="draggable storage col-lg-2">Storage</div>
  <div class="draggable pass col-lg-2">Kitchen Pass</div>
  <div class="draggable bar col-lg-2">Bar Area</div>
  <div class="draggable pos col-lg-2">POS</div>
</div>

<div>
  <div class="droppable">
  </div>
</div>


<script>
  // retrieve the coordinates saved in the database and render the elements accordingly
  var elements = <%= @restaurant.floorplans.to_json.html_safe %>;
  elements.forEach(function (element) {

  console.log('element.id:', element.id)
    var $elem = $("<div></div>");
      $elem.attr("id", element.id);
      $elem.attr("data-id", element.id);
      $elem.addClass("draggable");
      $elem.wrap("<div class='droppable'></div>")
      $elem.css({
        "position": "absolute",
        "top": element.top,
        "left": element.left,
        "height": element.height,
        "width": element.width,
        "background-color": element.background
      });
      console.log('$elem:', $elem);
      $elem.appendTo("body");

  });
</script>

app/views/floorplans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Top:</strong>
  <%= @floorplan.top %>
</p>

<p>
  <strong>Left:</strong>
  <%= @floorplan.left %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @floorplan.restaurant_id %>
</p>

<%= link_to 'Edit', edit_floorplan_path(@floorplan) %> |
<%= link_to 'Back', floorplans_path %>