config/routes.rb
Rails.application.routes.draw do
  resources :floorplans

  resources :restaurants

  resources :operators
  get "/register" => "operators#new"

  get "/restaurants/:id/floorplans" => "floorplans#new"
  post "/restaurants/:id/floorplans/add" => "floorplans#add"
  put '/restaurants/:id/floorplans/:floorplanId/update' => 'floorplans#update'

  root to: 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

end

app/models/operator.rb
class Operator < ApplicationRecord
  has_secure_password
  has_many :restaurants
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  before_action :set_operator, only: [:show, :edit, :update, :destroy]
  before_action :check_if_logged_out, only: [:new, :create]
  before_action :check_if_logged_in, only: [:edit, :update, :destroy]

  # GET /operators
  # GET /operators.json
  def index
    @operators = Operator.all
  end

  # GET /operators/1
  # GET /operators/1.json
  def show
    @restaurant = @operator.restaurants
  end

  # GET /operators/new
  def new
    @operator = Operator.new
  end

  # GET /operators/1/edit
  def edit
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(operator_params)

    respond_to do |format|
      if @operator.save
        format.html { redirect_to @operator, notice: 'Operator was successfully created.' }
        format.json { render :show, status: :created, location: @operator }
      else
        format.html { render :new }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operators/1
  # PATCH/PUT /operators/1.json
  def update
    respond_to do |format|
      if @operator.update(operator_params)
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { render :show, status: :ok, location: @operator }
      else
        format.html { render :edit }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator.destroy
    respond_to do |format|
      format.html { redirect_to operators_url, notice: 'Operator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operator
      @operator = Operator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operator_params
      params.require(:operator).permit(:name, :surname, :image, :email, :password_digest)
    end

    def check_if_logged_out
      if(@current_operator)
        flash[:error] = "You are already logged in."
        redirect_to(operator_path(session[:operator_id]))
      end
    end

    def check_if_logged_in
      if(!@current_operator)
        flash[:error] = "You need to be logged in."
        redirect_to("/login")
      end
    end

    def check_if_same_operator
      if(@current_operator.id != params["id"].to_i)
        flash[:error] = "You cannot visit that page."
        redirect_to(operator_path(@current_operator))
      end
    end


end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/views/operators/_form.html.erb
<%= form_for(operator) do |f| %>
  <% if operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% operator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>

  <!-- <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div> -->

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password_digest, placeholder: 'Password' %>
  </div>

  <!-- <div class="form-group">
  <%#= f.label :password_confirmation %>
  <%#= f.password_field :password_confirmation, class: "form-control", placeholder: 'Confirm Password'  %>
</div>

  <div class="field">
    <%#= f.label :password_digest %>
    <%#= f.text_field :password_digest %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operators/edit.html.erb
<h1 >Edit your Details</h1>

<%= render 'form', operator: @operator %>


<br>

<button type="button" class="btn btn-default"><%= link_to 'Back', operators_path %></button>
<small class="small">
  <%= link_to 'Back', operators_path %>
</small>

app/views/operators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Operators</h1>

<table class=" table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Image</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operators.each do |operator| %>
      <tr>
        <td><%= operator.name %></td>
        <td><%= operator.surname %></td>
        <td><%= operator.image %></td>
        <td><%= operator.email %></td>
        <td><%= link_to 'Show', operator %></td>
        <td><%= link_to 'Edit', edit_operator_path(operator) %></td>
        <td><%= link_to 'Destroy', operator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operator', new_operator_path %>

app/views/operators/new.html.erb
<h1>New Operator</h1>

<%= render 'form', operator: @operator %>

<%= link_to 'Back', operators_path %>

app/views/operators/show.html.erb
<div class="box">
  <div>
    <h3>Welcome Back, <br>
      <%= @operator.name %>!</h3>
  </div>

  <div class="image">
  <img src="<%=( @operator.image ) %>" alt="">
  </div>

  <p>
    <strong>Name:</strong>
    <%= @operator.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= @operator.surname %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @operator.email %>
  </p>

  <p>
    <strong>Restaurants:</strong>
          <% @restaurant.each do |restaurant| %>
              <br>
              <%= link_to(restaurant.name, restaurant_path(restaurant)) %>
          <% end %>
      </ul>
  </p>

  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_operator_path %></button>
  &nbsp
  <button type="button" class="btn btn-default"><%= link_to 'Add Restaurant', new_restaurant_path %></button>

</div>