config/routes.rb
Rails.application.routes.draw do
  resources :floorplans

  resources :restaurants

  resources :operators
  get "/register" => "operators#new"

  get "/restaurants/:id/floorplans" => "floorplans#new"
  post "/restaurants/:id/floorplans/add" => "floorplans#add"
  put '/restaurants/:id/floorplans/:floorplanId/update' => 'floorplans#update'

  root to: 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :operator
  has_many :floorplans
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  before_action :check_if_logged_in, only: [:create, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params['id'])
    @elements = @restaurant.floorplans
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params['id'])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.operator_id = @current_operator.id

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :image, :operator_id)
    end

    def check_if_logged_out
      if(@current_operator)
        flash[:error] = "You are already logged in."
        redirect_to(operator_path(session[:operator_id]))
      end
    end

    def check_if_logged_in
      if(!@current_operator)
        flash[:error] = "You need to be logged in."
        redirect_to("/login")
      end
    end

    def check_if_same_operator
      if(@current_operator.id != params["id"].to_i)
        flash[:error] = "You cannot visit that page."
        redirect_to(operator_path(@current_operator))
      end
    end

    def authorise
      unless @current_operator
        flash[:error] = "You need to be logged in for that"
        redirect_to "/login"
      end
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table class="table table-striped">
  <thead>
    <tr >
      <th>Name</th>
      <th>Address</th>
      <th>Image</th>
      <th>Operator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.image %></td>
        <td><%= restaurant.operator_id %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div id="menue-left" class="row">
  <div class="draggable margin table col-lg-2">Table</div>
  <div class="draggable margin station col-lg-2">Waiter Station</div>
  <div class="draggable margin storage col-lg-2">Storage</div>
  <div class="draggable margin pass col-lg-2">Kitchen Pass</div>
  <div class="draggable margin bar col-lg-2">Bar Area</div>
  <div class="draggable margin pos col-lg-2">POS</div>
</div>


<div>
  <div class="droppable">
  </div>
  <div class="square">
    <h3>Name:</h3>
    <h5><%= @restaurant.name %></h5><br>
    <h3>Address:</h3>
    <%= @restaurant.address %>
    <br><br>
    <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_restaurant_path(@restaurant) %></button>
    &nbsp
    <button type="button" class="btn btn-default"><%= link_to 'Back', operators_path(@operator) %></button>
  </div>

</div>





<script>
  // retrieve the coordinates saved in the database and render the elements accordingly
  var elements = <%= @restaurant.floorplans.to_json.html_safe %>;
  elements.forEach(function (element) {

  console.log('element.id:', element.id)
    var $elem = $("<div></div>");
      $elem.attr("id", element.id);
      $elem.attr("data-id", element.id);
      $elem.addClass("draggable");
      $elem.wrap("<div class='droppable'></div>")
      $elem.css({
        "position": "absolute",
        "top": element.top,
        "margin-top": "20px",
        "margin-left": "20px",
        "left": element.left,
        "height": element.height,
        "width": element.width,
        "background-color": element.background
      });
      console.log('$elem:', $elem);
      $elem.appendTo(".droppable");

  });
</script>