config/routes.rb
Rails.application.routes.draw do
  resources :floorplans

  resources :restaurants

  resources :operators
  get "/register" => "operators#new"

  get "/restaurants/:id/floorplans" => "floorplans#new"
  post "/restaurants/:id/floorplans/add" => "floorplans#add"
  put '/restaurants/:id/floorplans/:floorplanId/update' => 'floorplans#update'

  root to: 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeatThemAllApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-default navbar-fixed-top">
        <div>
          <div class="navbar-header">
            <a class="navbar-brand">Seat Them All</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if(@current_operator) %>
                <li>
                  <%= link_to(operator_path(@current_operator.id)) do %>
                    <%=@current_operator.name%>
                    <%=@current_operator.surname%>
                  <% end %>
                </li>
                <li>
                  <%= link_to(edit_operator_path(@current_operator.id)) do %>
                    Edit Profile
                  <% end %>
                </li>
                <li>
                  <a rel="nofollow" data-method="delete" href="/logout">Logout<i class="fa fa-sign-out"></i></a>
                </li>
                &nbsp
              <% else %>
                <li><a href="/login">Login</a></li>
                <li><a href="/register">Register</a></li>
              <% end %>
              &nbsp
            </ul>
            <ul class="nav navbar-nav">
              <% if(@current_operator) %>
                <li><%= link_to("Restaurant", "/restaurants/#{@restaurant_id}") %></li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
<br>
    <%= yield %>

  </body>

</html>